name: Build and Push Docker Image

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/build-and-push.yml
    types:
      - opened # default
      - synchronize # default
      - reopened # default
      - ready_for_review # draft -> ready
  release:
    types: [published]

env:
  REGISTRY: ghcr.io/bebit
  IMAGE_NAME: "${{ github.event_name == 'release' && 'python-mecab-builder' || 'python-mecab-builder-dev' }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
